name: counter-data-loader
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - openpyxl>=3.0.9
  - mysql-connector-python>=8.0.27
  - boto3>=1.19.7
  - botocore>=1.22.7
  - pip:
      # Used only for PyCharm debugging
      - pydevd-pycharm~=222.4345.23



